Metrics/BlockLength:
  Exclude:
    - 'rejoinder.gemspec'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: False

Style/GuardClause:
  Enabled: False

Style/IfUnlessModifier:
  Enabled: False

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'